### PR TITLE
fix!: Don't provide defaults for public repositories

### LINKED ISSUE #32: Conflicting values when using remote docker repositories with custom uri
First of all, thanks for the awesome work with this module, it really encapsulates well all the possibilities in a well organized way.

With that said, I think there's an issue with [remote repositories using custom uri](https://github.com/GoogleCloudPlatform/terraform-google-artifact-registry/issues/20), at least for remote docker repos.

This is my config:

```hcl
module "mcr-remote" {
  source  = "GoogleCloudPlatform/artifact-registry/google"
  version = "~> 0.2"

  project_id    = local.project_id
  location      = "eu"
  format        = "DOCKER"
  repository_id = "mcr-remote-eu"
  mode          = "REMOTE_REPOSITORY"

  remote_repository_config = {
    description                 = "remote mcr.microsoft.com"
    disable_upstream_validation = true
    docker_repository = {
      public_repository = null
      custom_repository = {
        uri = "https://mcr.microsoft.com"
      }
    }
  }

  labels = local.labels
}

```
It gives me the following error:

```shell
╷
│ Error: Conflicting configuration arguments
│
│   with module.artifact-registry.module.mcr-remote.google_artifact_registry_repository.repo,
│   on .terraform/modules/artifact-registry.mcr-remote/main.tf line 17, in resource "google_artifact_registry_repository" "repo":
│   17: resource "google_artifact_registry_repository" "repo" {
│
│ "remote_repository_config.0.docker_repository.0.custom_repository":
│ conflicts with
│ remote_repository_config.0.docker_repository.0.public_repository
```

Since we have the `public_repository = optional(string, "DOCKER_HUB")` with [a default value set](https://github.com/GoogleCloudPlatform/terraform-google-artifact-registry/blob/main/variables.tf#L105), it conflicts with whatever I try to set on the `custom_repository` object.

```hcl
variable "remote_repository_config" {
  type = object({
    description                 = optional(string)
    disable_upstream_validation = optional(bool, true)
    upstream_credentials = optional(object({
      username                = string
      password_secret_version = string
    }), null)
...
    docker_repository = optional(object({
      public_repository = optional(string, "DOCKER_HUB")
      custom_repository = optional(object({
        uri = string
      }), null)
    }), null)
...
  description = "Configuration specific for a Remote Repository."
  default     = null
}
```

To avoid it I believe we should either not set a default value for `public_repository` or add the following logic on the module:

```diff
      dynamic "docker_repository" {
        for_each = remote_repository_config.value.docker_repository[*]
        content {
-          public_repository = docker_repository.value.public_repository
+          public_repository = docker_repository.value.custom_repository == null ? docker_repository.value.public_repository : null
          dynamic "custom_repository" {
            for_each = docker_repository.value.custom_repository[*]
            content {
              uri = custom_repository.value.uri
            }
          }
        }
      }

```

To only use the default value if `custom_repository` is not set.

Let me know if I made any mistakes on wrong assumptions here.

### PR DESCRIPTION
**Pull request by frmrm**
This PR drops the default values for the `public_repository` keys under `remote_repository_config`. This fixes the underlying issue with configuring custom remote repositories, but it will require the data structures for folks using the public repositories to be a bit more verbose, unfortunately.

closes #32

### CODE REVIEW

**Comment by frmrm** [comment]
@prabhu34 - Got the CLA sorted out here. Would love to get this into the mainline so we don't have to maintain a fork. :)

**Comment by j8r** [comment]
Need a rebase now @frmrm.
@prabhu34 doesn't look like to be very active this days, maybe @apeabody could help us here?

**Review by apeabody — DISMISSED** [review]
Thanks for the contribution @frmrm!

Can you please rebase (or ideally add permission for maintainers).

Also, as this will be a breaking change, so we might need an upgrade guide similar to https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/master/docs/upgrading_to_v33.0.md

**Comment by apeabody** [comment]
(triggering the stuck lint workflow)

**Comment by apeabody** [comment]
From the lint test:

```
Checking for documentation generation
diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=autogen' '--exclude=*.tfvars' '--exclude=*metadata.yaml' /workspace/README.md /tmp/tmp.aG4F7F4BFl/generate_docs/workspace/README.md
56c56
< | remote\_repository\_config | Configuration specific for a Remote Repository. | <pre>object({<br>    description                 = optional(string)<br>    disable_upstream_validation = optional(bool, true)<br>    upstream_credentials = optional(object({<br>      username                = string<br>      password_secret_version = string<br>    }), null)<br>    apt_repository = optional(object({<br>      public_repository = optional(object({<br>        repository_base = string<br>        repository_path = string<br>      }), null)<br>    }), null)<br>    docker_repository = optional(object({<br>      public_repository = optional(string, "DOCKER_HUB")<br>      custom_repository = optional(object({<br>        uri = string<br>      }), null)<br>    }), null)<br>    maven_repository = optional(object({<br>      public_repository = optional(string, "MAVEN_CENTRAL")<br>      custom_repository = optional(object({<br>        uri = string<br>      }), null)<br>    }), null)<br>    npm_repository = optional(object({<br>      public_repository = optional(string, "NPMJS")<br>      custom_repository = optional(object({<br>        uri = string<br>      }), null)<br>    }), null)<br>    python_repository = optional(object({<br>      public_repository = optional(string, "PYPI")<br>      custom_repository = optional(object({<br>        uri = string<br>      }), null)<br>    }), null)<br>    yum_repository = optional(object({<br>      public_repository = optional(object({<br>        repository_base = string<br>        repository_path = string<br>      }), null)<br>    }), null)<br>  })</pre> | `null` | no |
---
> | remote\_repository\_config | Configuration specific for a Remote Repository. | <pre>object({<br>    description                 = optional(string)<br>    disable_upstream_validation = optional(bool, true)<br>    upstream_credentials = optional(object({<br>      username                = string<br>      password_secret_version = string<br>    }), null)<br>    apt_repository = optional(object({<br>      public_repository = optional(object({<br>        repository_base = string<br>        repository_path = string<br>      }), null)<br>    }), null)<br>    docker_repository = optional(object({<br>      public_repository = optional(string)<br>      custom_repository = optional(object({<br>        uri = string<br>      }), null)<br>    }), null)<br>    maven_repository = optional(object({<br>      public_repository = optional(string)<br>      custom_repository = optional(object({<br>        uri = string<br>      }), null)<br>    }), null)<br>    npm_repository = optional(object({<br>      public_repository = optional(string)<br>      custom_repository = optional(object({<br>        uri = string<br>      }), null)<br>    }), null)<br>    python_repository = optional(object({<br>      public_repository = optional(string)<br>      custom_repository = optional(object({<br>        uri = string<br>      }), null)<br>    }), null)<br>    yum_repository = optional(object({<br>      public_repository = optional(object({<br>        repository_base = string<br>        repository_path = string<br>      }), null)<br>    }), null)<br>  })</pre> | `null` | no |
Error: Documentation generation has not been run, please run the
'make docker_generate_docs' command and commit the above changes.
```

**Comment by frmrm** [comment]
@apeabody I have rebased on the latest `main` and run the doc generator. I'm honestly not sure where they stuck the checkbox to allow maintainers to send commits to my fork. 🧐

**Comment by frmrm** [comment]
Do you want the upgrade guide additions as a part of the same commit or as a subsequent commit?

**Comment by apeabody** [comment]
> Do you want the upgrade guide additions as a part of the same commit or as a subsequent commit?

I'd prefer everything in this PR, so we keep the repo aligned.  Thanks!

**Comment by apeabody** [comment]
> @apeabody I have rebased on the latest `main` and run the doc generator. I'm honestly not sure where they stuck the checkbox to allow maintainers to send commits to my fork. 🧐

Here is the doc, but I believe some Orgs may restrict it: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests

**Comment by frmrm** [comment]
That's probably the issue - our enterprise may have it set at the enterprise level and our OSS forks org is subject to that.

**Comment by frmrm** [comment]
@apeabody Updated. Let me know if that's what you're thinking or if further changes are needed.

**Comment by frmrm** [comment]
@apeabody Are you needing anything further from me on this?

**Comment by apeabody** [comment]
> @apeabody Are you needing anything further from me on this?

Thanks @frmrm! - Nothing at this time.

@prabhu34 - Can you please review this breaking change as well?

**Review by apeabody — APPROVED** [review]
Thanks for the contribution @frmrm!

**Pull request merged**
