### PR TITLE
chore(docs): Fix typo in labels

### PR DESCRIPTION
**Pull request by tanisdlj**

### CODE REVIEW

**Review by apeabody — CHANGES_REQUESTED** [review]
Thanks for the contribution @tanisdlj!

Can you please also the source here: https://github.com/GoogleCloudPlatform/terraform-google-artifact-registry/blob/main/variables.tf#L51

**Comment by tanisdlj** [comment]
> Thanks for the contribution @tanisdlj!
> 
> Can you please also the source here: https://github.com/GoogleCloudPlatform/terraform-google-artifact-registry/blob/main/variables.tf#L51

Done :)

**Review by prabhu34 — APPROVED** [review]
LGTM

**Pull request merged**
